In [ ]:
#正则化：
#正则化是指在损失函数中添加一个项，用于惩罚模型的复杂度。
#常用的正则化方法有L1正则化和L2正则化。
#L1正则化：在损失函数中添加一个项，用于惩罚模型的参数的绝对值之和。
#L2正则化：在损失函数中添加一个项，用于惩罚模型的参数的平方和。

#正则化的作用：
#正则化的作用是防止模型过拟合。
#过拟合是指模型在训练数据上的性能很好，但是在测试数据上的性能很差。
#正则化可以通过惩罚模型的参数的绝对值之和或平方和，来防止模型过拟合。

#正则化方法——dropout
#dropout是指在训练过程中，随机将神经网络中的一些神经元的输出设置为0。
#dropout可以防止模型过拟合，因为它强制模型学习多个子模型，而不是依赖于任何一个子模型。
#dropout的实现方法是在每个训练批次中，随机选择一些神经元，将它们的输出设置为0。
#在测试过程中，所有的神经元都被激活，但是它们的输出被缩放为原来的1/p，其中p是dropout的概率。
#这是因为在训练过程中，每个神经元的输出被缩放为1/p，以保持期望的输出不变。

#dropout层一般放在全连接层后面，激活函数后，用于防止过拟合。

#torch中api介绍
#torch.nn.Dropout(p=0.5, inplace=False)
#p是dropout的概率，默认值为0.5。
#inplace是一个布尔值，默认值为False。
#如果为True，那么在原地操作，否则返回一个新的张量。
#model.eval()
#在测试过程中，需要将模型设置为评估模式，即model.eval()。
#这是因为在评估模式下，dropout层会将所有的神经元都激活，但是它们的输出被缩放为原来的1/p，其中p是dropout的概率。
#这是因为在训练过程中，每个神经元的输出被缩放为1/p，以保持期望的输出不变。
#model.train()
#在训练过程中，需要将模型设置为训练模式，即model.train()。
#这是因为在训练模式下，dropout层会随机将一些神经元的输出设置为0。
#这是因为在训练过程中，每个神经元的输出被缩放为1/p，以保持期望的输出不变。

#示例
import torch
import torch.nn as nn 
input=torch.randint(0,10,size=(1,4)).float() #转为float类型，因为dropout层只支持float类型
linear1=nn.Linear(4,5)
x=linear1(input)
output=torch.relu(x)
dropout=nn.Dropout(p=0.4) #dropout层一般放在全连接层后面，用于防止过拟合。
print(output)
print(dropout(output))




tensor([[0.9445, 0.0000, 0.0000, 0.0000, 0.4797]], grad_fn=<ReluBackward0>)
tensor([[1.5742, 0.0000, 0.0000, 0.0000, 0.0000]], grad_fn=<MulBackward0>)


In [ ]:
#正则化方法——批量归一化
#批量归一化层（Batch Normalization Layer）是一种用于深度神经网络的正则化技术。
#它的主要作用是在每个训练批次中，对神经网络的输入进行归一化处理，以提高模型的训练速度和稳定性。
#具体来说，批量归一化层会对每个神经元的输入进行归一化，使得输入的分布保持在一个合理的范围内。
#这有助于避免梯度消失或爆炸问题，提高模型的收敛速度。
#在计算机视觉领域使用较多，如ResNet、Inception等模型。

#批量归一化层的工作原理如下：
#1. 对每个神经元的输入进行归一化处理，即将输入减去批次的均值，然后除以批次的标准差。
#2. 对归一化后的输入进行缩放和偏移，即乘以一个可学习的缩放因子（gamma），然后加上一个可学习的偏移因子（beta）。

#批量归一化层的优势在于：
#1. 加速模型训练：批量归一化层可以使得模型在每个训练批次中，输入的分布保持在一个合理的范围内，从而加速模型的训练过程。
#2. 提高模型稳定性：批量归一化层可以使得模型在训练过程中，对输入的扰动更加敏感，从而提高模型的稳定性。
#3. 减少过拟合风险：批量归一化层可以使得模型在训练过程中，对输入的扰动更加敏感，从而减少过拟合风险。

#BN层位置
#批量归一化层一般放在全连接层或卷积层后面，在激活函数之前，用于对输入进行归一化处理。
#具体来说，批量归一化层会对每个神经元的输入进行归一化，使得输入的分布保持在一个合理的范围内。
#这有助于避免梯度消失或爆炸问题，提高模型的收敛速度。

#api介绍
#torch.nn.BatchNorm1d(num_features, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
#num_features：输入的特征维度
#eps：一个小的常量，用于防止除0错误
#momentum：动量因子，用于更新运行时的均值和方差
#affine：是否对归一化后的输出进行缩放和偏移
#track_running_stats：是否跟踪运行时的均值和方差

#示例
import torch
import torch.nn as nn 
#照片为例
input=torch.randint(0,10,size=(1,2,3,4)).float()
#创建BN层
bn=torch.nn.BatchNorm2d(2,eps=1e-05,momentum=0.1,affine=True,track_running_stats=True) #2表示通道数，即照片的颜色通道数,这里转入的2是因为照片是2通道的，即RGB通道

#归一化处理
output=bn(input)
print(output)




tensor([[[[-0.1954, -1.2005, -0.1954,  1.1446],
          [ 1.1446,  0.4746,  0.1396, -1.5355],
          [ 1.1446, -1.5355,  1.1446, -0.5304]],

         [[ 1.7999, -0.9000, -1.2856,  0.6428],
          [ 0.2571,  1.4142,  0.2571, -0.9000],
          [-1.2856,  0.6428,  0.2571, -0.9000]]]],
       grad_fn=<NativeBatchNormBackward0>)
